---
-   name: Remove old version Nodejs/npm
    become: yes
    become_method: sudo
    apt:
        pkg: nodejs
        state: absent

-   name: Download nodejs 10.x deb pkg
    shell: |
        curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -

-   name: Install Nodejs/npm
    become: yes
    become_method: sudo
    apt:
        pkg: nodejs
        state: present

-   name: Install npm packages
    npm:
        path: "{{app_root}}"
        # production: yes
        state: present

-   name: Set google api key
    lineinfile:
        dest: "{{app_root}}/app.js"
        regexp: 'key: "<API-KEY>"'
        line: 'key: "{{google_api_key}}",'
        state: present

-   name: Build app
    shell: "cd {{app_root}} && npm run build"
