---
-   name: Clean app folder if already exists
    file:
        state: absent
        path: "{{ app_root }}"

-   name: Synchronization of src on the control machine to dest on the remote hosts
    synchronize:
        src: "{{playbook_dir}}/../.."
        dest: "{{app_root}}"
        rsync_opts:
            -   "--exclude=.git"
            -   "--exclude=node_modules"
            -   "--exclude=*__pychache__"
            -   "--exclude=*.venv"
            -   "--exclude=build"
            