"""empty message

Revision ID: b5e433463e76
Revises: 
Create Date: 2019-09-12 22:51:51.074172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e433463e76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=6), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('guest',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('coming', sa.Boolean(), nullable=True),
    sa.Column('food', sa.String(length=140), nullable=True),
    sa.Column('drink', sa.String(length=140), nullable=True),
    sa.Column('allergy', sa.String(length=255), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_guest_name'), 'guest', ['name'], unique=False)
    op.create_index(op.f('ix_guest_party_id'), 'guest', ['party_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_party_id'), table_name='guest')
    op.drop_index(op.f('ix_guest_name'), table_name='guest')
    op.drop_table('guest')
    op.drop_table('party')
    # ### end Alembic commands ###
